- name: install OSM required packages
  package:
    name: "{{ osm_required_packages[ansible_pkg_mgr] }}"
    state: present

- name: configure LXD
  block:
    - name: initialize LXD
      shell: "{{ item }}"
      with_items:
        - lxd init --auto
        - lxd waitready
    - name: stop lxd-bridge service
      systemd:
        name: lxd-bridge
        state: stopped
    - name: force systemd to reread configs
        daemon_reload: yes
    - name: create lxd-bridge configuration
      template:
        src: lxd-bridge.j2
        dest: /etc/default/lxd-bridge
        mode: 0755

- name: ensure docker and lxd-bridge services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - docker
    - lxd-bridge

- name: add devuser to LXD and Docker groups
  user:
    name: devuser
    groups: lxd, docker
    append: yes
