- name: install OSM required packages
  package:
    name: "{{ osm_required_packages[ansible_pkg_mgr] }}"
    state: present

- name: configure LXD
  block:
    - name: initialize LXD
      shell: "{{ item }}"
      with_items:
        - lxd init --auto
        - lxd waitready
    - name: stop lxd-bridge service
      systemd:
        name: lxd-bridge
        state: stopped
        daemon_reload: yes
    - name: create lxd-bridge configuration
      template:
        src: lxd-bridge.j2
        dest: /etc/default/lxd-bridge
        mode: 0755

- name: get default interface
  shell: route -n | awk '$1~/^0.0.0.0/ {print $8}'
  register: default_interface
  ignore_errors: False
  changed_when: False

- name: get ip of the default interface {{ default_interface.stdout }}
  shell: ip -o -4 a | grep {{ default_interface.stdout }} | awk '{split($4,a,"/"); print a[1]}'
  register: default_interface_ip
  ignore_errors: False
  changed_when: False

- name: get mtu of the default interface {{ default_interface.stdout }}
  shell: ip addr show {{ default_interface.stdout }} | perl -ne 'if (/mtu\s(\d+)/) {print $1;}'
  register: default_interface_mtu
  ignore_errors: False
  changed_when: False

- name: set lxdbr0 mtu to {{ default_interface_mtu.stdout }}
  shell: ifconfig lxdbr0 mtu {{ default_interface_mtu.stdout }}
  ignore_errors: False
  changed_when: False

- name: ensure docker and lxd-bridge services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - docker
    - lxd-bridge

- name: configure Docker Swarm
  block:
    - name: initialize Docker Swarm
      shell: docker swarm init --advertise-addr {{ default_interface_ip.stdout }}
      ignore_errors: False
      changed_when: False
    - name: create overlay network for Docker Swarm
      shell: docker network create --driver=overlay --attachable --opt com.docker.network.driver.mtu={{ default_interface_mtu.stdout }} netOSM
      ignore_errors: False
      changed_when: False

- name: add devuser to LXD and Docker groups
  user:
    name: devuser
    groups: lxd, docker
    append: yes
