---
##############################################################################
# Copyright (c) 2019 Ericsson Software Technology and others.
# Copyright (c) 2018 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

# set networking plugin to canal
- name: Set network plugin to canal
  lineinfile:
    path: "{{ remote_xci_path }}/.cache/repos/kubespray/opnfv_inventory/group_vars/k8s-cluster.yml"
    regexp: "^kube_network_plugin:.*"
    line: "kube_network_plugin: canal"

# vim: set ts=2 sw=2 expandtab:
